name: Build Standalone on Release
on:
  push:
    tags:
      - v[1-9].*

jobs:
<<<<<<< HEAD
  build-validation:
    name: Build Test
    uses: ./.github/workflows/run-lint.yaml
  build:
    name: Build and Upload Package
    uses: ./.github/workflows/build-and-publish-standalone.yaml
    needs:
      - build-validation
=======
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check package version
        env:
          TAG_VERSION: ${{github.ref_name}}
        run: ./scripts/check-version.sh $TAG_VERSION

  build:
    name: Build and Upload Package
    uses: ./.github/workflows/build-and-publish-standalone.yaml
    needs: check-version
>>>>>>> c541f81 (ci: add package version check (#396))
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      CI_BUILD_TAG: ${{github.ref_name}}
